### ISSUE TITLE
<Control>[ to escape

### ISSUE THREAD

**Issue by zaach** [misfo/jim#13]
I loathe the `esc` key.

**Comment by michaelficarra** [comment]
I wasn't aware anyone actually used that. Everyone I know who uses vim (on Linux, MacOS, and even Windows) swaps the escape key with capslock.

**Comment by zaach** [comment]
I swapped capslock with control instead since I use it for shortcuts in some other programs. ;)

**Comment by michaelficarra** [comment]
Regardless, this is a definite **+1** from me.

**Comment by misfo** [comment]
No love for `esc`?!?!?!?  I'll put this on the list. Thanks for the request!
