### ISSUE TITLE
`w` and `W` special EOL behavior in operations

### ISSUE THREAD

**Issue by misfo** [misfo/jim#18]
`w` and `W` motions that would normally move to the first non-blank of the next line (e.g. pressing `2w` on the second to last word in a line), only operate to the end of the line (i.e. `d2w` on the second to the last word of a line just deletes to the end of the line).  This special case needs to be implemented.

Here's the failing test case:
https://github.com/misfo/jim/blob/e5810c1b1e6ee028e903bb3edb447155a438be66/test/ace/operators.coffee#L18

**Comment by michaelficarra** [comment]
> should go to end of the line if part of an operation and would otherwise to to the beginning

yeah...

**Comment by misfo** [comment]
Hahaha. The sentence made so little sense that I had to include it, if only for entertainment value...
