### ISSUE TITLE
more common motions

### ISSUE THREAD

**Issue by michaelficarra** [misfo/jim#2]
I'd like to see `f` and `F` as well as `L`, `M`, and `H`. And since you just implemented `/`, I think it would be appropriate to complement it with `?`.

**Comment by misfo** [comment]
Definitely. `f`, `F`, `t`, and `T` are next on the list.

Thanks for all your work on CoffeeScript.  It's been a perfect language for the project

**Comment by michaelficarra** [comment]
@misfo: thanks for noticing my contributions! That totally made my day and verified that all the time I've put into it was worth it.

**Comment by misfo** [comment]
Got `f`, `F`, `t`, and `T` done, @michaelficarra.  Check it out http://misfo.github.com/jim/

**Comment by michaelficarra** [comment]
It's not working for me. Did you forget to push to `gh-pages`?

**Comment by misfo** [comment]
You may have to force reload... it's working for me at that URL

**Comment by michaelficarra** [comment]
Nope, cleared my cache and everything. Can't get it to work.

**Comment by misfo** [comment]
Hmm... what browser/platform are you on?  Firefox and chrome for Mac and Windows are working here

**Comment by michaelficarra** [comment]
Chrome 13 on 64-bit Fedora 14

**Comment by misfo** [comment]
Works on Ubuntu 32-bit Chrome 12 and Windows 32-bit Chrome canary build (14.0.823.0).  It must be a Chrome 13 specific issue.  I'll get Chrome 13 installed at some point and look into it.  Thanks for reporting!

**Comment by misfo** [comment]
I pushed `H`, `M`, and `L` out to gh-pages (force push over that visual mode fix that I tried).

Are the `t` and `f` motions still not working for you?

**Comment by michaelficarra** [comment]
`f` and `t` are working fine. `H`, `M`, and `L` aren't, unfortunately.

**edit**: It bothers me that I'm consistently having these problems. It's making me think it's my fault, but I couldn't imagine why.

**Comment by misfo** [comment]
@michaelficarra No worries. They must just be browser/platform specific issues...

I've added the fact that `H`, `M`, and `L` aren't working for you to #3 and I'm closing this one out.  Thanks for the command suggestions
