### ISSUE TITLE
issues with Chrome 13 on x64 Fedora 14

### ISSUE THREAD

**Issue by misfo** [misfo/jim#3]
Visual mode gives no visual feedback of where the selection is, even though regular Ace selections do.

Also, `H`, `M`, and `L` do not work either:
https://github.com/misfo/jim/issues/2#issuecomment-1612678

**Comment by michaelficarra** [comment]
I actually don't ever see the visual mode selection, whether linewise or not. It still behaves properly, I just have no visual feedback. Again, Chrome 13 on x64 Fedora 14

**Comment by misfo** [comment]
Can you see selections when you make them in ace?:
http://ajaxorg.github.com/ace/

**Comment by michaelficarra** [comment]
yes

**Comment by misfo** [comment]
Ok. I'll try to reproduce those issues and dig into what's going on. Thanks again for reporting

**Comment by misfo** [comment]
I wasn't able to reproduce the issues on Chrome 13 Ubuntu.

Since Ace draws the selections and you were able to see selections in the latest Ace, I updated the Ace submodule to the latest.  Maybe that will fix the issue:
http://misfo.github.com/jim/

If that doesn't fix it, can you try some selections again in Ace the idleFingers theme (what Jim uses) here:
http://ajaxorg.github.com/ace/

**Comment by michaelficarra** [comment]
Selection works fine in Ace, even under the idleFingers theme. Selection using Jim does not work using `v` and `V` (by work, I mean I don't see it, but it behaves properly). I can, however, use my mouse to make selections and the escape key to clear them. But Jim doesn't behave as if these selections have been made, which is understandable.

**Comment by misfo** [comment]
So I've changed the visual mode movement to closer match what Ace keybindings do when moving the selection.  Give that a shot.
http://misfo.github.com/jim/

It's kind of a crap shoot trying to find the fix for this because I can't reproduce the problem. I know that some change selection rendering event isn't being fired correctly in your browser, but I can't really tell which one, so I'm going to have to try a bunch of little changes if you'll bear with me...

**Comment by michaelficarra** [comment]
Nope, sorry. Better luck next time.

I wish it was spitting out errors in the console or something so I could be of more help. Maybe add some (more) helpful logging? I get the `setMode`s and `@buffer`s if that helps...

**Comment by misfo** [comment]
This may be a bit hacky, but I pushed out a commit to gh-pages that just forces the event to fire after any visual mode motion.  Let me know if that fixes it for you.  Thanks
http://misfo.github.com/jim/

**Comment by michaelficarra** [comment]
That one just made things worse. Now normal visual mode doesn't work properly and linewise visual mode breaks on the first use. I tried deleting three lines and it deleted everything until the end of the file. Also, still no visual feedback.

**Comment by misfo** [comment]
I'm sorry, man. But I'm gonna have to punt on these issues for now until I find a machine on which I can reproduce them.  They're too hard to debug when I have to bug you each time I try a fix...

Because of the way linewise visual mode works in Vim (the cursor doesn't have to "stay" at either end of the selection) I may have to change how visual mode works anyways.  If/when that happens I'll ping you to see if it improved the situation for you.

Thanks for testing all this stuff out for me.  Let me know if the situation changes!

**Comment by michaelficarra** [comment]
Update: `V` works for the first line now, disappears once you move. `v` is still never visible.

**Comment by misfo** [comment]
@michaelficarra I pushed to `gh-pages` with a newer version of Ace that had some selection fixes.  If you give that a try and it still doesn't work, I'll push a commit out with a bunch of relevant `console.log`'s so we can get this figured out.

**Comment by michaelficarra** [comment]
Awesome! Just checked it out and it looks like selection is working perfectly now. Thanks.

**edit:** also, `H`, `M`, and `L` are working now

**Comment by misfo** [comment]
Good to hear!
